// import ThemeProvider from '@/components/ThemeProvider'
import './globals.css';
import { Space_Grotesk } from 'next/font/google';
import '../css/main.css';
const inter = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
